# Generated by Django 6.0.2 on 2026-02-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wallettransaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='plan_type',
            field=models.CharField(choices=[('SME', 'SME'), ('GIFTING', 'Gifting'), ('CG', 'Corporate Gifting'), ('CG_LITE', 'CG Lite'), ('AWOOF', 'Awoof Gifting'), ('DIRECT', 'Direct Data'), ('DATACARD', 'Data Card'), ('SMILE_DIRECT', 'Smile Direct'), ('SPECIAL', 'Special Plan')], default='SME', max_length=20),
        ),
    ]
