# Generated by Django 5.1.2 on 2025-10-15 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airtime_provider_alter_datacategory_api_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airtime',
        ),
        migrations.RemoveField(
            model_name='dataplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='datatransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='virtualplan',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providerplan',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Price Table', 'verbose_name_plural': 'Price Tables'},
        ),
        migrations.AlterModelOptions(
            name='sellrequest',
            options={'verbose_name': 'Sell Request', 'verbose_name_plural': 'Sell Requests'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RemoveField(
            model_name='pricetable',
            name='size_mb',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='size_mb',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('GLO', 'Glo'), ('9MOBILE', '9mobile')], default='MTN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='phone_number',
            field=models.CharField(default='08000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='DEFAULT_REF', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Airtime Purchase', 'Airtime Purchase'), ('Data Purchase', 'Data Purchase'), ('Wallet Funding', 'Wallet Funding'), ('Withdrawal', 'Withdrawal')], default='Wallet Funding', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='my_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'Airtel'), ('GLO', 'Glo'), ('9MOBILE', '9mobile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='vtu_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DataCategory',
        ),
        migrations.DeleteModel(
            name='DataPlan',
        ),
        migrations.DeleteModel(
            name='DataTransaction',
        ),
        migrations.DeleteModel(
            name='VirtualPlan',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProviderPlan',
        ),
    ]
