# Generated by Django 5.1.2 on 2025-10-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_airtime_remove_dataplan_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='data_type',
            field=models.CharField(choices=[('SME', 'SME'), ('AWUF', 'AWUF'), ('GIFTING', 'GIFTING')], default='SME', max_length=20),
        ),
    ]
