# Generated by Django 5.1.2 on 2025-10-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pricetable_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='api_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
