# Generated by Django 5.1.2 on 2025-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pricetable_api_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='data_type',
            field=models.CharField(choices=[('SME', 'SME'), ('GIFTING', 'Gifting')], default='SME', max_length=20),
        ),
    ]
