# Generated by Django 5.1.2 on 2025-11-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pricetable_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricetable',
            old_name='data_type',
            new_name='plan_type',
        ),
    ]
