# Generated by Django 5.1.2 on 2025-11-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_data_type_pricetable_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
